### ISSUE TITLE
TypeError: Incorrect response MIME type. Expected 'application/wasm'

### ISSUE THREAD

**Issue by tennisonchan** [mdn/webassembly-examples#5]
Since `application/wasm` isn't an official MIME type yet, https://github.com/WebAssembly/spec/issues/573, in case you got the type error of an incorrect response MIME type, you can add the following line in file `/etc/mime.types` and then restart the server.
```
application/wasm    wasm
```

FYI:
https://bugs.python.org/issue31670
https://github.com/python/cpython/pull/3861

**Comment by tetravalence** [comment]
Hi, I've done what you said but I still get the error messages
`wasm streaming compile failed: TypeError: Response has unsupported MIME type`
and
`falling back to ArrayBuffer instantiation`
by using Hello World mdn example in Firefox 59.0.2

**Comment by timmyjose** [comment]
Just wanted to make a note here for macOS users. For me, I was running into the same issue, and the suggestions online (of adding a new MIME type to `/etc/mime` does not work for macOS since there is no such file).

The following snippet *does not* work on macOS:
```
<script>
    WebAssembly.instantiateStreaming(fetch('my-file.wasm'))
      .then(obj => {
         // do something, say, print to console
         console.log(obj.instance.exports.my_func());
      });
  </script>
```

whereas the following *does work*:
```
<script>
  fetch('my-file.wasm').then(response => 
  	response.arrayBuffer()
  ).then(bytes => 
    WebAssembly.instantiate(bytes)
  ).then(obj => {
      console.log(obj.instance.exports.my_func());
  });
  </script>
```
Posting it here in case other frustrated people come across this looking for a solution on macOS.

**Comment by richlum** [comment]
similar issue using 'web server for chrome' on linux.  Adapted timmyjose solution while trying to follow along https://developer.mozilla.org/en-US/docs/WebAssembly/Text_format_to_wasm  

    <script>
      var importObject = {
        imports: { imported_func: arg => console.log(arg) }
      };
      fetch('simple.wasm').
      then(response => response.arrayBuffer()).
      then(bytes => WebAssembly.instantiate(bytes, importObject)).
      then(obj => obj.instance.exports.exported_func());

**Comment by lukewagner** [comment]
I think `python2 -m SimpleHTTPServer` and `python3 -m http.server` should work for local testing nowadays.

Note that `instantiateStreaming(Response)` provides much better performance than `instantiate(ArrayBuffer)` so ideally an app would only use `instantiate(ArrayBuffer)` as a fallback when `instantiateStreaming` failed.  (E.g., I think Unity and Emscripten do this.)

**Comment by H-arshit** [comment]
> <script>
>   fetch('my-file.wasm').then(response => 
>   	response.arrayBuffer()
>   ).then(bytes => 
>     WebAssembly.instantiate(bytes)
>   ).then(obj => {
>       console.log(obj.instance.exports.my_func());
>   });
>   </script>

where do we have make these changes?

**Comment by lucidBrot** [comment]
> I think `python2 -m SimpleHTTPServer` and `python3 -m http.server` should work for local testing nowadays.
> 
> Note that `instantiateStreaming(Response)` provides much better performance than `instantiate(ArrayBuffer)` so ideally an app would only use `instantiate(ArrayBuffer)` as a fallback when `instantiateStreaming` failed. (E.g., I think Unity and Emscripten do this.)

That did not directly work for me, however [this gist](https://gist.github.com/HaiyangXu/ec88cbdce3cdbac7b8d5) provides a python server that does work

**Comment by VertikaJain** [comment]
You need to install **static-server** rather than **http-server**. This is because the WebAssembly module needs to be served with a MIME type of application/wasm, and the MIME type is provided in the static-server package.
For confirmation, you can cross check in your package-lock.json after installing both these packages using npm and compare the respective _"requires"_ fields. The static-server will be having _"mime": "^version_name"_ . 
Check out my [github repository on AssemblyScript](https://github.com/VertikaJain/webAssembly-assemblyScript) for more detailed implementation.
